#端口号
server:
  port: 8080

spring:
  application:
    name: springboot-mybatis-neo4j #服务名
  banner:
    image:
      location:
        classpath: banner.jpg

  datasource:
    driver-class-name: org.neo4j.jdbc.http.HttpDriver
    name: neo4j
    password: anyi666
#    url: jdbc:neo4j:http://localhost:7474
    url: jdbc:neo4j:http://localhost:11006
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    #url: jdbc:mysql://101.132.155.41:3306/suining_artmember?characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2b8
#    url: jdbc:mysql://127.0.0.1:3306/suining_artmember?characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2b8
#    #url: jdbc:mysql://106.54.67.119:3306/artmember?characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2b8
#    #url: jdbc:mysql://localhost:3306/artmember?characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2b8
#    username: root
#    #password: Macro@!@#
#    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#分页pageHelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
